vim.api.nvim_create_user_command('Anrcy', function() require("anrcy").run_highlighted_jobs() end, { range = true })
vim.api.nvim_create_user_command('AnrcyQuickGet', function() require("anrcy").get_highlighted_url() end, { range = true })
vim.api.nvim_create_user_command('AnrcyBookmark', function() require("anrcy").set_bookmark() end, { range = true })
vim.api.nvim_create_user_command('AnrcyShowCurl', function() require("anrcy").show_curl() end, { range = true })

vim.api.nvim_create_user_command('AnrcyExecuteBookmark', function() require("anrcy").execute_bookmark() end, {})
vim.api.nvim_create_user_command('AnrcyClear', function() require("anrcy").clear_jobs() end, {})
vim.api.nvim_create_user_command('AnrcyRepeat', function() require("anrcy").repeat_last() end, {})
vim.api.nvim_create_user_command('AnrcyTemplate', function() require("anrcy").insert_template() end, {})
vim.api.nvim_create_user_command('AnrcyHistory', function() require("anrcy").show_history() end, {})
